### ISSUE TITLE
Confused about refreshing ads

### ISSUE THREAD

**Issue by nakamin** [Avocarrot/android-demo-app#13]
When a user refreshes the feed, the ads also need to be refreshed. The way it's done in the sample app is not very great: https://github.com/Avocarrot/android-demo-app/blob/master/app/src/main/java/com/avocarrot/avocarrotdemoapp/fragments/ListExampleFragment.java#L77 This is recreating the adapter, and the Avocarrot ad stream each time the user refreshes. This can have performance impacts since a lot of objects are being created. Is there a refresh method, or a load method that can be used instead to trigger the placements to be refreshed?

**Comment by tsiougkosn** [comment]
Hi there,

If you update the data of your Adapter and call _notifyDataSetChanged()_ the Avocarrot SDK will be notified for the changes and show ads in the new data set.

Let me know if that helps you,
Nikos
